/* ============================================================
   VAULT DATA — themes, titles, tag pools
   Hand-curated topic lists per theme, ordered topically so
   "proximity linking" produces coherent neighborhoods.
   ============================================================ */

window.VAULT_DATA = {
  themes: [
    {
      id: 'mind',
      name: 'Philosophy of Mind',
      folder: '01 Mind',
      color: '#38ff9c',
      tagPool: ['consciousness','mind','philosophy','qualia','self','perception','free-will','intentionality','phenomenology'],
      titles: [
        'What is consciousness',
        'The hard problem',
        'Qualia',
        'Phenomenal vs access consciousness',
        'Higher-order theories',
        'Global workspace theory',
        'Integrated information theory',
        'Functionalism',
        'Type identity theory',
        'Eliminative materialism',
        'The mind-body problem',
        'Cartesian dualism',
        'Property dualism',
        'Panpsychism',
        'Anomalous monism',
        'Mental causation',
        'Folk psychology',
        'Theory of mind',
        'Intentionality',
        'The Chinese Room',
        "Mary's Room",
        'Philosophical zombies',
        'What is it like to be a bat',
        'Free will',
        'Compatibilism',
        'Libertarian free will',
        'Hard determinism',
        'The frame problem',
        'Embodied cognition',
        'The extended mind thesis',
        '4E cognition',
        'Predictive processing',
        'The Bayesian brain',
        'Active inference',
        'The free energy principle',
        'Markov blankets',
        'Attention schema theory',
        'The binding problem',
        'Self-models',
        'Heterophenomenology',
        "Dennett's multiple drafts",
        'Naive realism',
        'Direct vs indirect perception',
        'Affordances',
        'Consciousness as performance',
      ],
    },
    {
      id: 'ml',
      name: 'Machine Learning',
      folder: '02 ML',
      color: '#7ab8ff',
      tagPool: ['ml','neural-net','transformer','training','optimization','rl','generative','alignment','interp'],
      titles: [
        'Backpropagation',
        'Gradient descent',
        'Stochastic gradient descent',
        'The Adam optimizer',
        'Batch normalization',
        'Layer normalization',
        'Dropout',
        'Residual connections',
        'Attention mechanisms',
        'Self-attention',
        'Multi-head attention',
        'Positional encoding',
        'Transformer architecture',
        'BERT',
        'The GPT family',
        'Encoder-decoder models',
        'Vision transformers',
        'Diffusion models',
        'Score matching',
        'DDPM',
        'Classifier-free guidance',
        'Variational autoencoders',
        'GANs',
        'Mode collapse',
        'Convolutional networks',
        'Pooling layers',
        'Receptive fields',
        'Object detection',
        'YOLO',
        'Mask R-CNN',
        'Reinforcement learning',
        'Q-learning',
        'Policy gradients',
        'PPO',
        'Actor-critic methods',
        'Reward shaping',
        'Exploration vs exploitation',
        'Multi-armed bandits',
        'Imitation learning',
        'World models',
        'Model-based RL',
        'AlphaGo',
        'AlphaFold',
        'Mixture of experts',
        'LoRA fine-tuning',
        'RLHF',
        'Constitutional AI',
        'Mechanistic interpretability',
        'Sparse autoencoders for features',
        'Scaling laws',
      ],
    },
    {
      id: 'info',
      name: 'Information Theory',
      folder: '03 Information',
      color: '#b18cff',
      tagPool: ['information','entropy','compression','coding','complexity','channel','probability'],
      titles: [
        'Shannon entropy',
        'Mutual information',
        'KL divergence',
        'Cross-entropy',
        'Kolmogorov complexity',
        'Algorithmic probability',
        'Solomonoff induction',
        'Minimum description length',
        'Channel capacity',
        'The noisy channel coding theorem',
        'The source coding theorem',
        'Huffman coding',
        'Arithmetic coding',
        'Compression',
        'Error-correcting codes',
        'Hamming codes',
        'Reed-Solomon codes',
        'LDPC codes',
        'Information geometry',
        'Fisher information',
        'Rate-distortion theory',
        'The information bottleneck',
        'The maximum entropy principle',
        'Thermodynamic entropy',
        "Maxwell's demon",
        "Landauer's principle",
        'Reversible computing',
        'Quantum information',
        'The Holevo bound',
        'The Bekenstein bound',
      ],
    },
    {
      id: 'writing',
      name: 'Writing Craft',
      folder: '04 Writing',
      color: '#ff7ad9',
      tagPool: ['writing','craft','narrative','prose','voice','essay','journalism','style'],
      titles: [
        'Show don\u2019t tell',
        'Free indirect discourse',
        'Close third person',
        'First person reliable vs unreliable',
        'The narrative arc',
        "Freytag's pyramid",
        'Three-act structure',
        'Beat sheets',
        'Save the Cat',
        "The hero's journey",
        'The inciting incident',
        'Rising action',
        'Climax',
        'Denouement',
        'Voice',
        'Diction',
        'Sentence rhythm',
        'The em-dash',
        'The semicolon defense',
        'Strunk and White revisited',
        "Orwell's six rules",
        'Killing your darlings',
        'Drafting fast, editing slow',
        'Cutting adverbs',
        'The passive voice',
        'The Hemingway minimum',
        'Long-form essays',
        'Lyric essay',
        'Braided essay',
        'Memoir vs autobiography',
        'The personal essay',
        'Place writing',
        'Nature writing',
        'Travel writing',
        'Reportage',
        'New journalism',
        'Gonzo journalism',
        'Literary nonfiction',
        'The lede',
        'The kicker',
      ],
    },
    {
      id: 'cogsci',
      name: 'Cognitive Science',
      folder: '05 Cognition',
      color: '#5eead4',
      tagPool: ['cognition','memory','attention','bias','perception','learning','language','reasoning'],
      titles: [
        'Working memory',
        'Long-term memory',
        'Episodic memory',
        'Semantic memory',
        'Procedural memory',
        'Memory consolidation',
        'Sleep and memory',
        'Forgetting curves',
        'Spaced repetition',
        'Encoding specificity',
        'Levels of processing',
        'Dual coding theory',
        'Cognitive load',
        'Chunking',
        'Expert intuition',
        'System 1 and System 2',
        'Heuristics and biases',
        'The anchoring effect',
        'The availability heuristic',
        'Framing effects',
        'Loss aversion',
        'Prospect theory',
        'Confirmation bias',
        'Hindsight bias',
        'The Stroop effect',
        'Attention',
        'Inattentional blindness',
        'Change blindness',
        'The cocktail party effect',
        'Top-down vs bottom-up processing',
        'Perceptual organization',
        'Gestalt principles',
        'Categorization',
        'Prototype theory',
        'Exemplar theory',
        'Concept learning',
        'Analogical reasoning',
        'Conceptual metaphor',
        'Embodied semantics',
        'Mental imagery',
      ],
    },
    {
      id: 'arch',
      name: 'Software Architecture',
      folder: '06 Software',
      color: '#ffb84a',
      tagPool: ['architecture','distributed','design-pattern','scaling','observability','microservices','reliability'],
      titles: [
        'Microservices',
        'Monoliths',
        'The modular monolith',
        'Event-driven architecture',
        'CQRS',
        'Event sourcing',
        'Domain-driven design',
        'Bounded contexts',
        'Ubiquitous language',
        'Hexagonal architecture',
        'Clean architecture',
        'Onion architecture',
        'Layered architecture',
        'Service mesh',
        'API gateways',
        'The BFF pattern',
        'GraphQL',
        'REST',
        'gRPC',
        'Protocol buffers',
        'Database per service',
        'The saga pattern',
        'Two-phase commit',
        'Eventual consistency',
        'CAP theorem',
        'PACELC',
        'Sharding',
        'Replication',
        'Read replicas',
        'Caching strategies',
        'Cache invalidation',
        'CDNs',
        'Load balancing',
        'Circuit breakers',
        'Bulkheads',
        'Retries and backoff',
        'Idempotency',
        'Distributed tracing',
        'Observability',
        'SLI, SLO, SLA',
        'Chaos engineering',
        'Blue-green deployment',
        'Canary releases',
        'Feature flags',
        'The twelve-factor app',
      ],
    },
    {
      id: 'urban',
      name: 'Urbanism',
      folder: '07 Cities',
      color: '#ff5a5a',
      tagPool: ['cities','transport','housing','urbanism','planning','public-space','streets'],
      titles: [
        'Jane Jacobs',
        'Death and Life of Great American Cities',
        'Mixed-use zoning',
        'Single-use zoning',
        'Euclidean zoning',
        'Form-based codes',
        'The 15-minute city',
        'Walkability',
        'The Walk Score',
        'Bicycle infrastructure',
        'Protected bike lanes',
        'Dutch intersections',
        'Woonerf',
        'Shared streets',
        'The stroad',
        'Strong Towns',
        'Suburban retrofit',
        'Infill development',
        'Missing middle housing',
        'Accessory dwelling units',
        'YIMBY',
        'NIMBY',
        'Density',
        'Floor area ratio',
        'Transit-oriented development',
        'Bus rapid transit',
        'Light rail',
        'Heavy rail',
        'Active transport',
        'Pedestrian malls',
        'The Str\u00f8get effect',
        'Public space',
        'Third places',
        'Eyes on the street',
        'New Urbanism',
      ],
    },
    {
      id: 'music',
      name: 'Music Theory',
      folder: '08 Music',
      color: '#fbbf24',
      tagPool: ['music','theory','harmony','rhythm','scales','jazz','classical','counterpoint'],
      titles: [
        'Equal temperament',
        'Just intonation',
        'Pythagorean tuning',
        'The circle of fifths',
        'Modes of the major scale',
        'Ionian',
        'Dorian',
        'Phrygian',
        'Lydian',
        'Mixolydian',
        'Aeolian',
        'Locrian',
        'Harmonic minor',
        'Melodic minor',
        'Chord function',
        'Tonic, subdominant, dominant',
        'Secondary dominants',
        'Tritone substitution',
        'Voice leading',
        'Counterpoint',
        'Species counterpoint',
        'Fugue form',
        'Sonata form',
        'Theme and variations',
        'Rondo form',
        'Twelve-tone technique',
        'Serialism',
        'Spectralism',
        'Microtonality',
        'Polyrhythm',
        'Polymeter',
        'Hemiola',
        'Syncopation',
        'Swing feel',
        'Bebop changes',
        'Modal jazz',
        'Coltrane changes',
        'Negative harmony',
        'The backdoor cadence',
        'Lydian chromatic concept',
      ],
    },
    {
      id: 'cook',
      name: 'Cooking',
      folder: '09 Cooking',
      color: '#f97316',
      tagPool: ['cooking','food','technique','fermentation','flavor','science','baking'],
      titles: [
        'The Maillard reaction',
        'Caramelization',
        'Emulsification',
        'Mayonnaise',
        'Hollandaise',
        'Beurre blanc',
        'Gluten development',
        'Hydration percentage',
        'Sourdough levain',
        'Lactic vs acetic fermentation',
        'Sous vide',
        'Pressure cooking',
        'Confit',
        'Brining',
        'Dry-aging',
        'Sear and rest',
        'Reverse sear',
        'Mirepoix',
        'Sofrito',
        'Suya spice',
        'Garam masala',
        'Chinese five spice',
        'Umami',
        'Glutamate',
        'Inosinate synergy',
        'Salt as enhancer',
        'Acid balance',
        'Fat as flavor carrier',
        'Texture contrast',
        'Plating principles',
        'Mise en place',
        'The brigade system',
        'Knife skills',
        'Sharpening vs honing',
        'Cooking whole animals',
      ],
    },
    {
      id: 'math',
      name: 'Mathematics',
      folder: '10 Math',
      color: '#a78bfa',
      tagPool: ['math','algebra','topology','logic','analysis','probability','geometry','foundations'],
      titles: [
        'Set theory',
        "Russell's paradox",
        'Zermelo-Fraenkel set theory',
        'The axiom of choice',
        'Ordinals',
        'Cardinals',
        'The continuum hypothesis',
        "G\u00f6del's incompleteness",
        'The halting problem',
        'Turing machines',
        'Lambda calculus',
        'The Curry-Howard correspondence',
        'Type theory',
        'Category theory',
        'Functors',
        'Natural transformations',
        'Monads in category theory',
        'Topology basics',
        'Manifolds',
        'Homotopy',
        'Homology',
        'The fundamental group',
        'Differential geometry',
        'Riemannian manifolds',
        'Lie groups',
        'Algebraic geometry',
        'Galois theory',
        'Group theory',
        'Rings and fields',
        'Modules',
        'Linear algebra',
        'Eigenvalues and eigenvectors',
        'The spectral theorem',
        'Singular value decomposition',
        'Convex optimization',
        'Lagrange multipliers',
        'Measure theory',
        'Lebesgue integration',
        'Probability spaces',
        'Markov chains',
        'Martingales',
        'Ergodic theory',
        'Number theory',
        'Prime distribution',
        'The Riemann hypothesis',
      ],
    },
    {
      id: 'hist',
      name: 'History of Science',
      folder: '11 Science History',
      color: '#fcd34d',
      tagPool: ['history','science-history','physics','biology','chemistry','paradigm','revolution'],
      titles: [
        'The Scientific Revolution',
        'Copernican heliocentrism',
        "Galileo's telescope",
        "Kepler's laws",
        "Newton's Principia",
        'The calculus priority dispute',
        'The Royal Society',
        "Boyle's law",
        'The phlogiston theory',
        'Lavoisier and oxygen',
        'The atomic hypothesis',
        "Dalton's atoms",
        "Mendeleev's periodic table",
        "Faraday's field",
        "Maxwell's equations",
        'The luminiferous aether',
        'The Michelson-Morley experiment',
        'Special relativity',
        'General relativity',
        'The Bohr atom',
        'The Copenhagen interpretation',
        "Schr\u00f6dinger's equation",
        'The EPR paradox',
        "Bell's inequalities",
        'The Manhattan Project',
        'The discovery of DNA',
        'The central dogma of biology',
        'The Modern Synthesis',
        'Continental drift',
        'Plate tectonics',
        'The Big Bang',
        'The cosmic microwave background',
        'Inflation',
        'The Standard Model',
        'The Higgs boson',
        'Linnaean taxonomy',
        'The germ theory of disease',
        "Pasteur's experiments",
        'The Human Genome Project',
        'The reproducibility crisis',
      ],
    },
    {
      id: 'prod',
      name: 'Notes & Productivity',
      folder: '12 PKM',
      color: '#34d399',
      tagPool: ['productivity','pkm','notes','workflow','attention','gtd','reading','tools'],
      titles: [
        'Zettelkasten',
        'Niklas Luhmann',
        'Atomic notes',
        'Evergreen notes',
        "Andy Matuschak's notes",
        'Maps of Content',
        'The 12 favorite problems',
        'PARA method',
        "Tiago Forte's CODE",
        'Building a Second Brain',
        'Progressive summarization',
        'Note-taking vs note-making',
        'Linking your thinking',
        'Bidirectional links',
        'Block references',
        'Daily notes',
        'Periodic notes',
        'The weekly review',
        "David Allen's GTD",
        'Inboxes and processing',
        'Capture-clarify-organize-reflect-engage',
        'The two-minute rule',
        'The Eisenhower matrix',
        'Deep work',
        'Cal Newport',
        'Time-blocking',
        'Calendar as task list',
        'The Pomodoro technique',
        "Maker's vs manager's schedule",
        'Slow thinking time',
        'Walking meetings',
        'Morning pages',
        'Julia Cameron',
        "The artist's date",
        'Writing as thinking',
        'The blank page problem',
        'Anti-libraries',
        'The Lindy effect',
        'Commonplace books',
        'Marginalia',
        'Reading systems',
        'Active reading',
        'How to Take Smart Notes',
        'Spaced repetition for ideas',
        'Anki',
        'Discourse graphs',
        'Roam-style outliners',
        'Logseq',
        'Obsidian',
        'Plain text futures',
        'Sync tooling',
        'Vault structure',
        'File over app',
        'Markdown as canonical format',
        'The note-taking treadmill',
      ],
    },
  ],
};
